version: '3.7'

services:
  app:
    container_name: sysexam_app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: builder
    volumes:
      - ./:/app
    environment:
      PGPASSWORD: test
    tty: true
    depends_on: 
      - db

  db:
    container_name: sysexam_db
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - ./build/containers/db:/docker-entrypoint-initdb.d
  
  web:
    container_name: sysexam_nginx
    build: ./build/containers/nginx
    volumes:
      - ./logs:/var/log/nginx
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8080:80 
    depends_on:
      - app